### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by jamessding** [jamessding/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a green background in HTML for the racetrack.
- [x] Create an image element with a src of the car image.
- [x] Set the position of the car to the top left of the window.
- [x] Make sure the car is facing towards the right.
