### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by jamessding** [jamessding/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a data model that includes which way the car is facing
- [x] Store the data in localStorage with JSON
- [x] Listen for 'keydown' events on the document
- [x] add EventListener to 'keydown' events which changes direction of car and updates data model depending on which arrow is pressed
- [x] create CSS classes for each direction to change the image direction
