### ISSUE TITLE
Issue 3 - User can start their car.

### ISSUE THREAD

**Issue by jamessding** [jamessding/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add an eventListener for 'keydown' event with a function that only runs when the spacebar key is pressed
- [x] setInterval with two arguments, a function that moves the car forward a few pixels, and 16 milliseconds
- [x] Add a location to data model to hold the car's x and y coordinates on the page.
- [x] change the car's top and left box offset styles in the function to move the car
