### ISSUE TITLE
Issue 4 - User can steer their car.

### ISSUE THREAD

**Issue by jamessding** [jamessding/driving-game#7]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [ ] modify moveCar function to move forward based on the current direction of the car
- [ ] whenever car direction changes, clear the current setInterval and replace it with new setInterval that moves car in correct direction
- [ ] update the x and y location of car each time the car moves
